// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type AskStreamEvent struct {
	// Token content from the LLM stream
	Token string `json:"token"`
	// True when the stream is complete
	Done bool `json:"done"`
	// Error message if streaming failed
	Error *string `json:"error,omitempty"`
}

type Job struct {
	ID           string        `json:"id"`
	Type         string        `json:"type"`
	Status       string        `json:"status"`
	Progress     int           `json:"progress"`
	Total        int           `json:"total"`
	Result       *IngestResult `json:"result,omitempty"`
	Error        *string       `json:"error,omitempty"`
	StartedAt    time.Time     `json:"startedAt"`
	CompletedAt  *time.Time    `json:"completedAt,omitempty"`
	DirPath      *string       `json:"dirPath,omitempty"`
	PendingFiles *int          `json:"pendingFiles,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
